### ISSUE TITLE
[Bug]: Control Page: Fetch Error

### ISSUE THREAD

**Issue by M4r71nW** [stereum-dev/ethereum-node#1933]
### Environment

production

### Bug Description

Control Page: Node: No Data, please check the service

![Screenshot from 2024-07-08 09-58-53](https://github.com/stereum-dev/ethereum-node/assets/151830077/a8de81d8-4e77-45b4-b546-2bbc1835cec4)

```
Error occured to get Beacon node status:  TypeError: Cannot read properties of undefined (reading 'clt')
    at Monitoring.getCurrentEpochSlot (/tmp/.mount_Stereuy5J84e/resources/app.asar/index.js:8:453356)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /tmp/.mount_Stereuy5J84e/resources/app.asar/index.js:8:676160
    at async node:electron/js2c/browser_init:2:98069
```

### Launcher Version

2.2.1

### Operating System

Linux

### Affected Service (if applicable)

Lodestar

### Logs (if applicable)

```shell
#27: Jul-08 07:37:41.999[]                 [32minfo[39m: Synced - slot: 2043488 - head: 0x68e2…323d - exec-block: valid(1886046 0x9455…) - finalized: 0xdfe7…5d23:63857 - peers: 100

#26:     at Object.handler (file:///usr/app/packages/api/src/utils/server/genericJsonServer.ts:45:23)

#25:     at Object.registerValidator (file:///usr/app/packages/beacon-node/src/api/impl/validator/index.ts:1321:7)

#24:     at ExecutionBuilderHttp.registerValidator (file:///usr/app/packages/beacon-node/src/execution/builder/http.ts:95:7)

#23:     at Object.request [as registerValidator] (file:///usr/app/packages/api/src/utils/client/client.ts:96:23)

#22:     at HttpClient.requestWithBody (file:///usr/app/packages/api/src/utils/client/httpClient.ts:330:19)

#21:     at processTicksAndRejections (node:internal/process/task_queues:95:5)

#20:     at HttpClient.wrappedFetch [as fetch] (file:///usr/app/packages/api/src/utils/client/fetch.ts:12:11)

#19: FetchError: Request to http://localhost:8661/eth/v1/builder/validators failed, reason: 

#18: Jul-08 07:37:37.261[rest]            [31merror[39m: Req req-33ed registerValidator error - Request to http://localhost:8661/eth/v1/builder/validators failed, reason: 

#17: Jul-08 07:37:30.001[]                 [32minfo[39m: Synced - slot: 2043487 - head: 0x07f7…c3a4 - exec-block: valid(1886045 0x81b4…) - finalized: 0xe78f…0d8e:63856 - peers: 101
```

### Acknowledgment

- [X] I have checked the existing bugs and confirmed this issue is not already reported.

**Comment by mabasian** [comment]
This fetch error on the control page only occurs when using the Lodestar and Erigon pair. The issue started after both services were updated.
