### ISSUE TITLE
Teku doesn't start

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum-node#350]
Using "Staking Setup", when teku is installed the service keeps restarting all the time with the following error message:
```
2022-06-01 10:02:08,223 main INFO Configuring logging for destination: console
2022-06-01 10:02:08,225 main INFO Logging includes events: true
2022-06-01 10:02:08,226 main INFO Logging includes validator duties: true
2022-06-01 10:02:08,226 main INFO Logging includes color: true
2022-06-01 10:02:08,238 main INFO Include P2P warnings set to: false
2022-06-01 10:02:08.516 FATAL - Could not access Validator api keystore file /opt/app/data/teku_api_keystore
tech.pegasys.teku.infrastructure.exceptions.InvalidConfigurationException: Could not access Validator api keystore file /opt/app/data/teku_api_keystore
at tech.pegasys.teku.validator.client.restapi.ValidatorRestApiConfig$ValidatorRestApiConfigBuilder.lambda$build$0(ValidatorRestApiConfig.java:190) ~[teku-validator-client-22.5.0.jar:22.5.0]
at java.util.Optional.ifPresentOrElse(Unknown Source) ~[?:?]
at tech.pegasys.teku.validator.client.restapi.ValidatorRestApiConfig$ValidatorRestApiConfigBuilder.build(ValidatorRestApiConfig.java:186) ~[teku-validator-client-22.5.0.jar:22.5.0]
at tech.pegasys.teku.config.TekuConfiguration$Builder.build(TekuConfiguration.java:243) ~[teku-22.5.0.jar:22.5.0]
at tech.pegasys.teku.cli.BeaconNodeCommand.tekuConfiguration(BeaconNodeCommand.java:371) ~[teku-22.5.0.jar:22.5.0]
at tech.pegasys.teku.cli.BeaconNodeCommand.call(BeaconNodeCommand.java:295) ~[teku-22.5.0.jar:22.5.0]
at tech.pegasys.teku.cli.BeaconNodeCommand.call(BeaconNodeCommand.java:74) ~[teku-22.5.0.jar:22.5.0]
at picocli.CommandLine.executeUserObject(CommandLine.java:1953) ~[picocli-4.6.3.jar:4.6.3]
at picocli.CommandLine.access$1300(CommandLine.java:145) ~[picocli-4.6.3.jar:4.6.3]
at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358) ~[picocli-4.6.3.jar:4.6.3]
at picocli.CommandLine$RunLast.handle(CommandLine.java:2352) ~[picocli-4.6.3.jar:4.6.3]
at picocli.CommandLine$RunLast.handle(CommandLine.java:2314) ~[picocli-4.6.3.jar:4.6.3]
at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179) ~[picocli-4.6.3.jar:4.6.3]
at picocli.CommandLine$RunLast.execute(CommandLine.java:2316) ~[picocli-4.6.3.jar:4.6.3]
at picocli.CommandLine.execute(CommandLine.java:2078) ~[picocli-4.6.3.jar:4.6.3]
at tech.pegasys.teku.cli.BeaconNodeCommand.parse(BeaconNodeCommand.java:239) ~[teku-22.5.0.jar:22.5.0]
at tech.pegasys.teku.Teku.start(Teku.java:63) ~[teku-22.5.0.jar:22.5.0]
at tech.pegasys.teku.Teku.startFromCLIArgs(Teku.java:86) ~[teku-22.5.0.jar:22.5.0]
at tech.pegasys.teku.Teku.main(Teku.java:40) ~[teku-22.5.0.jar:22.5.0]
Could not access Validator api keystore file /opt/app/data/teku_api_keystore

To display full help:
teku [COMMAND] --help
```

**Comment by NeoPlays** [comment]
Runs after validator import.
Should the keystore file and all other files be generated with the setup?
I think this would fix this

Same goes for nimbus

**Comment by stefa2k** [comment]
Yes, please generate the keystore so the beacon service can startup and run properly.
